## Model Training

In [1]:
import numpy as  np
import pandas as pd

In [2]:
df = pd.read_csv('../data/Analysis.csv')

In [3]:
df.head(2)

,Unnamed: 0.1,Unnamed: 0,customer_id,age,gender,income,product_category,browsing_time,pages_viewed,previous_purchases,discount_used,purchased
0,0,0,109721,56.0,Male,40702.27,Fashion,28.25,19.0,3.0,Yes,1
1,1,1,135306,22.0,Male,14907.71,Grocery,11.25,3.0,4.0,No,1

In [10]:
X  = df.drop(columns=['Unnamed: 0.1','Unnamed: 0','customer_id','purchased'])
y  = df['purchased']

In [ ]:
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

,age,gender,income,product_category,browsing_time,pages_viewed,previous_purchases,discount_used
0,56.0,Male,40702.27,Fashion,28.25,19.0,3.0,Yes
1,22.0,Male,14907.71,Grocery,11.25,3.0,4.0,No
2,43.0,Female,15860.81,Home,22.55,6.0,6.0,Yes
3,45.0,Male,47451.61,Grocery,24.87,6.0,2.0,Yes
4,39.0,Female,33790.07,Grocery,19.40,9.0,5.0,No
...,...,...,...,...,...,...,...,...
45099,22.0,Female,41799.57,Fashion,19.22,40.0,3.0,Yes
45100,48.0,Male,41479.60,Beauty,9.42,8.0,1.0,No
45101,29.0,Female,34557.05,Grocery,23.61,19.0,2.0,No
45102,62.0,Female,44933.76,Sports,9.82,14.0,3.0,No
45103,64.0,Unknown,15530.94,Home,24.21,5.0,4.0,No